### ISSUE TITLE
Can not set UI port

### ISSUE THREAD

**Issue by cfoellmann** [tiredofit/docker-mailhog#2]
Setting the UI port does not work with `UI_LISTEN_PORT=80`

I think it is because there are to many "d"s here:
https://github.com/tiredofit/docker-mailhog/blob/8f16b8431b244f5e5b51b89aa75961362462047d/install/etc/services.available/10-mailhog/run#L18

right?

**Comment by tiredofit** [comment]
https://github.com/tiredofit/docker-mailhog/commit/89e6069cd790e9b6c07d369f2d9e62f0a4eecf95 should resolve - looks like there were a few issues with spelling and blank characters

**Comment by cfoellmann** [comment]
Works! Thanks
